name: Update image tag on values.yml file

on:
   push:
    branches: [ "dev", "main" ]

jobs:
  update_helm_values:
    name: Update Helm values file
    runs-on: ubuntu-latest
    needs: push_to_registry

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update image tag value
        run: |
          chart_dir="config/python-app"
          new_image_tag=${{ github.sha }}

          sed -i "s/^  tag: .*/  tag: $new_image_tag/" "$chart_dir/values.yaml"

      - name: Commit changes
        run: |
            git config --global user.name 'Noe Quiroz'
            git config --global user.email ${{ secrets.EMAIL }}
            git commit -am "updating image tag"
            git push