name: Update image tag on values.yml file

on:
  workflow_run:
    workflows: ['Build and Push Docker Image to Docker Hub']
    types:
      - completed

jobs:
  update_helm_values:
    name: Update Helm values file
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update image tag value
        run: |
          chart_dir="config/python-app"
          new_image_tag=${{ github.sha }}

          sed -i "s/^  tag: .*/  tag: $new_image_tag/" "$chart_dir/values.yaml"

      - name: Commit changes
        run: |
            git config --global user.name 'Noe Quiroz'
            git config --global user.email 'jafir.quiroz@gmail.com'
            git commit -am "updating image tag"
            git push